# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SQLiteDemo' do
  use_frameworks!

  pod "FMDB"
  pod 'SICategory', '~> 1.6.1'
  pod 'SINetworkManager', '~> 1.0'

end
